export const MENU_TEXT_CATALOG = Object.freeze({
    'menu.brand.title': 'Curvios Clash',
    'menu.panels.settings.title': 'Einstellungen',
    'menu.panels.controls.title': 'Steuerung',
    'menu.panels.profiles.title': 'Spieler',
    'menu.panels.portals.title': 'Portale / Map',
    'menu.panels.expert.title': 'Expertenbereich',
    'menu.navigation.back.label': 'Zurück',
    'menu.level4.presets.title': 'Vorlagen',
    'menu.context.session.single': 'Einzelspieler',
    'menu.context.session.splitscreen': 'Geteilter Bildschirm',
    'menu.context.session.multiplayer': 'Mehrspieler',
    'menu.context.mode.normal': 'Klassisch',
    'menu.context.mode.fight': 'Kampf',
    'menu.context.mode.arcade': 'Arcade',
    'menu.context.mode.quick_action': 'Schnellstart',
    'menu.context.section.controls': 'Steuerung',
    'menu.context.section.mobile_controls': 'Mobile',
    'menu.context.section.gameplay': 'Spielregeln',
    'menu.context.section.audio': 'Audio',
    'menu.context.section.graphics': 'Grafik & Kamera',
    'menu.context.section.recording': 'Aufnahme',
    'menu.context.section.hud': 'HUD',
    'menu.context.section.advanced_map': 'Map-Details',
    'menu.context.section.tools': 'Spieler',
    'menu.context.section.presets': 'Vorlagen',
    'menu.context.section.utilities': 'Werkzeuge',
    'menu.context.level4.title': 'Einstellungen',
    'menu.context.game.step': 'Match vorbereiten',
    'menu.context.custom.step': 'Spielstil wählen',
    'menu.context.custom.summary': 'Sofortstart oder Setup',
    'menu.context.dirty': 'ungespeicherte Änderungen',
    'menu.context.saved': 'alles gespeichert',
    'menu.navigation.open.label': 'Öffnen',
    'menu.utility.tutorial.label': 'Neu hier? Steuerung lernen',
    'menu.utility.tutorial.completed.label': 'Tutorial abgeschlossen — nochmal spielen',
    'menu.level2.arcade.description': 'Fliege durch Sektoren, sammle Punkte und verbessere deinen Arcade-Lauf.',
    'menu.level2.fight.description': 'Kämpfe mit Waffen gegen andere Piloten und erreiche das Abschussziel.',
    'menu.level2.normal.description': 'Weiche Hindernissen und Spuren aus und bleibe als Letzter im Rennen.',
    'menu.level4.tabs.audio.label': 'Audio',
    'menu.level4.tabs.graphics.label': 'Grafik & Kamera',
    'menu.level4.tabs.recording.label': 'Aufnahme',
    'menu.level4.tabs.hud.label': 'HUD',
    'menu.utility.settings.label': 'Einstellungen',
    'menu.utility.controls.label': 'Steuerung',
    'menu.utility.profiles.label': 'Spieler',
    'menu.utility.tools.label': 'Werkzeuge',
    'menu.utility.lock.label': 'Sperren',
    'menu.expert.locked.title': 'Expertenbereich',
    'menu.expert.password.label': 'Passwort',
    'menu.expert.unlock.label': 'Freischalten',
    'menu.expert.cancel.label': 'Abbrechen',
    'menu.level2.tutorial.label': 'Classic-Tutorial starten',
    'menu.level2.tutorial.description': 'Steuerung, Boost, Hindernisse und Power-ups auf einem kurzen Parcours lernen.',
    'menu.multiplayer.redirect.title': 'Weiterleitung',
    'menu.multiplayer.inline.title': 'Lobby & Bereitschaft',
    'menu.multiplayer.inline.subtitle': 'Lobby verbinden, Teilnehmer prüfen und gemeinsam starten.',
    'menu.multiplayer.inline.host.label': 'Host',
    'menu.multiplayer.inline.join.label': 'Join',
    'menu.camera.perspective.classic.label': 'Spielgetreu',
    'menu.camera.perspective.cinematic_soft.label': 'Cinematic Soft',
    'menu.camera.perspective.cinematic_action.label': 'Cinematic Action',
    'menu.panels.settings.open.label': 'Spieloptionen öffnen',
    'menu.panels.controls.open.label': 'Steuerung öffnen',
    'menu.panels.profiles.open.label': 'Spieler öffnen',
    'menu.panels.portals.open.label': 'Map-Details öffnen',
    'menu.debug.build.title': 'Build-Information',
    'menu.debug.build.copy.label': 'Build-Info kopieren',
    'menu.level3.rail.kicker': 'Startvorbereitung',
    'menu.level3.rail.title': 'Vorbereitung',
    'menu.level3.map.description': 'Größe, Favoriten und Vorschau für den Start',
    'menu.level3.map.filter.all': 'Alle Größen',
    'menu.level3.map.filter.small': 'Klein',
    'menu.level3.map.filter.medium': 'Mittel',
    'menu.level3.map.filter.large': 'Groß',
    'menu.level3.map.select.label': 'Karte direkt wählen',
    'menu.level3.map.favorite.label': 'Favoriten',
    'menu.level3.map.recent.label': 'Zuletzt benutzt',
    'menu.level3.vehicle.description': 'Fahrzeuge im 3D-Hangar betrachten und direkt auswählen',
    'menu.level3.vehicle.filter.all': 'Alle Klassen',
    'menu.level3.vehicle.filter.light': 'Leicht',
    'menu.level3.vehicle.filter.medium': 'Mittel',
    'menu.level3.vehicle.filter.heavy': 'Schwer',
    'menu.level3.vehicle.armor.label': 'Panzerung',
    'menu.level3.vehicle.agility.label': 'Wendigkeit',
    'menu.level3.vehicle.control.label': 'Kontrolle',
    'menu.level3.vehicle.p1.label': 'Direktauswahl Pilot 1',
    'menu.level3.vehicle.p2.label': 'Direktauswahl Pilot 2',
    'menu.level3.match.description': 'Die wichtigsten Regeln für den Start',
    'menu.level3.match.flight_style.title': 'Flugstil',
    'menu.level3.match.bots.label': 'Bots:',
    'menu.level3.match.bot_difficulty.label': 'Bot-Schwierigkeit',
    'menu.level3.match.wins.label': 'Siege zum Gewinn:',
    'menu.level3.match.ghost.title': 'Selbstduell',
    'menu.level3.match.ghost_mode.label': 'Ghost-Wiedergabe',
    'menu.level3.match.ghost_collision.label': 'Ghost-Spur-Kollision',
    'menu.level3.match.arcade_run.title': 'Arcade-Lauf',
    'menu.level3.match.arcade_sectors.label': 'Sektoren bis zum Sieg:',
    'menu.level3.match.bot_type.label': 'Bot-Typ',
    'menu.level3.match.kill_limit.label': 'Abschusslimit',
    'menu.level3.presets.title': 'Vorlagen',
    'menu.level3.presets.description': 'Fertige Einstellungen für Training, Arcade und Kampf',
    'menu.level3.multiplayer.inline.title': 'Lobby & Bereitschaft',
    'menu.level3.multiplayer.inline.description': 'Lobby verbinden, Teilnehmer prüfen und gemeinsam starten',
    'menu.level3.multiplayer.open_lobbies.label': 'Offene Online-Lobbys',
    'menu.level3.multiplayer.code.label': 'Lobby-Code',
    'menu.level3.multiplayer.host_address.label': 'Host-Adresse',
    'menu.level4.tabs.controls.label': 'Steuerung',
    'menu.level4.tabs.mobile_controls.label': 'Mobile',
    'menu.level4.tabs.gameplay.label': 'Spielregeln',
    'menu.level4.tabs.advanced_map.label': 'Map-Details',
    'menu.level4.tabs.tools.label': 'Spieler',
    'menu.level4.tabs.presets.label': 'Vorlagen',
    'menu.level4.tabs.utilities.label': 'Werkzeuge',
    'menu.level4.controls.mouse_steering.label': 'Maus-Lenkung für Spieler 1 (Tasten bleiben für Aktionen aktiv)',
    'menu.level4.controls.gamepad_vibration.label': 'Controller-Vibration bei Treffern und Explosionen in der Nähe',
    'menu.level4.controls.smooth_steering.label': 'Sanfte Lenkung (Tastatur fährt die Kurve in ~55 ms an)',
    'menu.level4.controls.player1_keys.label': 'Tasten Spieler 1',
    'menu.level4.controls.player2_keys.label': 'Tasten Spieler 2',
    'menu.level4.controls.global_key.label': 'Globale Taste',
    'menu.level4.mobile.title': 'Mobile-Feineinstellung',
    'menu.level4.mobile.tilt_sensitivity.label': 'Neigungs-Empfindlichkeit:',
    'menu.level4.mobile.arcade_assist.label': 'Arcade Assist',
    'menu.level4.mobile.pitch_mode.label': 'Höhensteuerung',
    'menu.level4.mobile.tilt_live.label': 'Live-Neigungsanzeige',
    'menu.level4.mobile.sensor_hz.label': 'Sensor-Hz anzeigen',
    'menu.level4.gameplay.speed.label': 'Geschwindigkeit:',
    'menu.level4.gameplay.turn.label': 'Lenkempfindlichkeit:',
    'menu.level4.gameplay.plane_size.label': 'Flugzeuggröße:',
    'menu.level4.gameplay.trail_width.label': 'Strahldicke:',
    'menu.level4.gameplay.gap_size.label': 'Lückengröße:',
    'menu.level4.gameplay.gap_frequency.label': 'Lückenhäufigkeit:',
    'menu.level4.gameplay.item_amount.label': 'Item-Menge:',
    'menu.level4.gameplay.auto_roll.label': 'Auto-Roll aktiv',
    'menu.level4.gameplay.invert_pitch_p1.label': 'Pitch umkehren P1 (Stick hoch / W = Nase runter)',
    'menu.level4.gameplay.invert_pitch_p2.label': 'Pitch umkehren P2 (Stick hoch / Num 8 = Nase runter)',
    'menu.level4.gameplay.invert_pitch_p3.label': 'Pitch umkehren P3 (Stick hoch / I = Nase runter)',
    'menu.level4.gameplay.fire_rate.label': 'Schussintervall:',
    'menu.level4.gameplay.lockon.label': 'Zielerfassungswinkel:',
    'menu.level4.gameplay.checkpoint_glow.label': 'Leuchten des nächsten Checkpoints:',
    'menu.level4.gameplay.mg_aim.label': 'MG-Zielsuchradius an Spuren:',
    'menu.level4.gameplay.fight_hp.label': 'Spieler-HP im Kampf:',
    'menu.level4.gameplay.fight_damage.label': 'MG-Schaden im Kampf:',
    'menu.level4.graphics.style.label': 'Grafikstil',
    'menu.level4.graphics.map_brightness.label': 'Karten-Helligkeit',
    'menu.level4.graphics.view_distance.label': 'Sichtweite:',
    'menu.level4.graphics.shadow_quality.label': 'Schattenqualität:',
    'menu.level4.graphics.bloom_quality.label': 'Bloom:',
    'menu.level4.camera.perspective.label': 'Video-Perspektive',
    'menu.level4.recording.profile.label': 'Aufnahmeprofil',
    'menu.level4.recording.hud_mode.label': 'HUD in der Aufnahme',
    'menu.level4.recording.orientation.label': 'Format des Cinematic-Videos',
    'menu.level4.hud.scale.label': 'HUD-Größe:',
    'menu.level4.hud.opacity.label': 'HUD-Deckkraft:',
    'menu.level4.hud.color.label': 'HUD-Farbschema',
    'menu.level4.map.portals.label': 'Portale aktiviert',
    'menu.level4.map.portal_count.label': 'Anzahl Portal-Eingänge:',
    'menu.level4.map.planar_levels.label': 'Anzahl Ebenen:',
    'menu.level4.map.planar_mode.label': 'Planar Modus (kein Pitch)',
    'menu.level1.single.label': 'Einzelspieler',
    'menu.level1.multiplayer.label': 'Mehrspieler',
    'menu.level1.splitscreen.label': 'Geteilter Bildschirm',
    'menu.level1.help.title': 'Spielart',
    'menu.level1.help.next': 'Danach: Spielstil wählen',
    'menu.level2.title': 'Spielstil wählen',
    'menu.level2.quick.title': 'Weitere Schnellstarts',
    'menu.level2.quick.hint': 'Diese Aktionen starten sofort mit vorbereiteten oder zufälligen Einstellungen.',
    'menu.level2.quick_last.label': 'Sofort spielen',
    'menu.level2.quick_random.label': 'Zufallskarte starten',
    'menu.level2.mode.title': 'Wie möchtest du spielen?',
    'menu.level2.arcade.label': 'Arcade',
    'menu.level2.fight.label': 'Kampf',
    'menu.level2.normal.label': 'Klassisch',
    'menu.level3.title': 'Match vorbereiten',
    'menu.level3.summary.title': 'Deine Auswahl',
    'menu.level3.map.title': 'Karte',
    'menu.level3.vehicle.title': 'Flugzeug',
    'menu.level3.matchfields.title': 'Regeln & Match',
    'menu.level3.matchfields.hint': 'Wähle die wichtigsten Regeln. Weitere Details findest du unter Erweitert.',
    'menu.level3.start.label': 'Spiel starten',
    'menu.level3.open_level4.label': 'Einstellungen',
    'menu.level3.reset.label': 'Zurücksetzen',
    'menu.level4.title': 'Einstellungen',
    'menu.level4.reset.label': 'Spiel-, Grafik- & Aufnahmeoptionen zurücksetzen',
    'menu.level4.close.label': 'Schließen',
    'menu.level4.controls.title': 'Steuerung',
    'menu.level4.controls.reset_keys.label': 'Standard-Tasten wiederherstellen',
    'menu.level4.gameplay.title': 'Spieloptionen',
    'menu.level4.advanced_map.title': 'Map-Details',
    'menu.level4.tools.title': 'Gespeicherte Einstellungen',
    'menu.level4.tools.profile_name.label': 'Name',
    'menu.level4.tools.profile_save.label': 'Einstellungen speichern',
    'menu.level4.tools.profile_list.label': 'Gespeicherte Einstellungen',
    'menu.level4.tools.profile_load.label': 'Laden',
    'menu.level4.tools.profile_delete.label': 'Löschen',
    'menu.level4.tools.profile_duplicate.label': 'Duplizieren',
    'menu.level4.tools.profile_default.label': 'Als Standard markieren',
    'menu.level4.tools.profile_transfer.label': 'Einstellungen übertragen',
    'menu.level4.tools.profile_export.label': 'Exportieren',
    'menu.level4.tools.profile_import.label': 'Importieren',
    'menu.level4.tools.preset_catalog.label': 'Vorlage',
    'menu.level4.tools.preset_apply.label': 'Vorlage anwenden',
    'menu.level4.tools.preset_name.label': 'Name der neuen Vorlage',
    'menu.level4.tools.preset_save_open.label': 'Als freie Vorlage speichern',
    'menu.level4.tools.preset_save_fixed.label': 'Als verbindliche Vorlage speichern',
    'menu.level4.tools.preset_delete.label': 'Vorlage löschen',
    'menu.level4.tools.map_editor.label': '3D-Map-Editor öffnen',
    'menu.level4.tools.vehicle_editor.label': 'Vehicle-Editor öffnen',
    'menu.level4.tools.open_developer.label': 'Developer-Bereich öffnen',
    'menu.developer.title': 'Developer',
    'menu.developer.open_debug.label': 'Debug / Info öffnen',
    'menu.developer.text_override.title': 'Textkatalog-Override',
    'menu.developer.text_override.apply.label': 'Override setzen',
    'menu.developer.text_override.clear.label': 'Override löschen',
    'menu.developer.telemetry.title': 'Entwicklungs-Telemetrie',
    'menu.debug.title': 'Debug / Info',
    'menu.tools.import.label': 'Importieren',
    'menu.tools.export_code.label': 'Code exportieren',
    'menu.tools.export_json.label': 'JSON exportieren',
    'menu.multiplayer.title': 'Multiplayer',
    'menu.multiplayer.host.label': 'Spiel erstellen',
    'menu.multiplayer.join.label': 'Spiel beitreten',
    'menu.multiplayer.lobby.code': 'Lobby-Code',
    'menu.multiplayer.lobby.players': 'Spieler',
    'menu.multiplayer.lobby.ready': 'Bereit',
    'menu.multiplayer.lobby.start': 'Match starten',
    'menu.multiplayer.lobby.waiting': 'Warte auf Spieler…',
    'menu.multiplayer.lobby.settings': 'Lobby-Einstellungen',
    'menu.multiplayer.lobby.leave': 'Lobby verlassen',
    'menu.multiplayer.lobby.back': 'Zurück',
    'menu.multiplayer.lobby.ip': 'Server-IP',
    'menu.multiplayer.lobby.map': 'Map',
    'menu.multiplayer.lobby.mode': 'Modus',
    'menu.multiplayer.lobby.rounds': 'Runden',
    'menu.multiplayer.lobby.ping': 'Ping',
    'menu.multiplayer.error.full': 'Lobby ist voll (max. 10 Spieler).',
    'menu.multiplayer.error.connection': 'Verbindung fehlgeschlagen.',
    'menu.arcade.title': 'Arcade Run',
    'menu.arcade.summary': 'Sektoren meistern, Punkte sammeln und nach dem Sieg freiwillig weiterspielen',
    'menu.arcade.runline.label': 'Aktueller Arcade-Layer',
    'menu.arcade.start.label': 'Arcade Run starten',
    'menu.arcade.seed.title': 'Seed und Challenge',
    'menu.arcade.seed.current.label': 'Run-Seed',
    'menu.arcade.seed.daily.label': 'Daily',
    'menu.arcade.seed.reroll.label': 'Seed neu rollen',
    'menu.arcade.seed.copy.label': 'Seed als Challenge nutzen',
    'menu.arcade.seed.rerolled.toast': 'Arcade-Seed aktualisiert.',
    'menu.arcade.seed.challenge.toast': 'Challenge-Seed bereit',
    'menu.arcade.hud.title': 'Run-Übersicht',
    'menu.arcade.hud.score.label': 'Score',
    'menu.arcade.hud.multiplier.label': 'x-Multi',
    'menu.arcade.hud.sector.label': 'Sektor',
    'menu.arcade.hud.chain.label': 'Combo',
    'menu.arcade.postrun.title': 'Post-Run Feedback',
    'menu.arcade.postrun.last.label': 'Letzter Start',
    'menu.arcade.postrun.empty': 'Noch kein Arcade-Run gestartet.',
    'menu.arcade.postrun.replay.label': 'Replay exportieren',
    'menu.arcade.postrun.daily.label': 'Daily starten',
    'menu.arcade.postrun.replay.toast.ready': 'Replay-Fallback bereit.',
    'menu.arcade.postrun.replay.toast.disabled': 'Replay ist deaktiviert.',
    'menu.arcade.postrun.replay.toast.empty': 'Kein Replay verfügbar.',
    'menu.arcade.postrun.daily.toast': 'Daily-Challenge startet mit Seed',
    'menu.arcade.mastery.title': 'Fahrzeugfortschritt',
    'menu.arcade.mastery.current.label': 'Fahrzeug',
    'menu.arcade.mastery.progress.label': 'Level',
    'game.killcam.label': 'KILLCAM',
});

export function listMenuTextCatalogEntries() {
    return Object.entries(MENU_TEXT_CATALOG).map(([id, text]) => ({ id, text }));
}

export function resolveMenuCatalogText(textId, fallback = '') {
    const normalizedTextId = typeof textId === 'string' ? textId.trim() : '';
    if (!normalizedTextId) return fallback;
    return MENU_TEXT_CATALOG[normalizedTextId] || fallback;
}
