import {
    SETTINGS_CHANGE_KEYS,
    SETTINGS_CHANGE_PATH_ENTRIES,
} from './SettingsChangeKeys.js';

export const SETTINGS_FIELD_NORMALIZERS = Object.freeze({
    BOOLEAN: 'boolean',
    ENUM: 'enum',
    IDENTIFIER: 'identifier',
    NUMBER: 'number',
    CONTRACT: 'contract',
});

const PRESET_FIELD_NORMALIZER_BY_CHANGE_KEY = new Map([
    [SETTINGS_CHANGE_KEYS.MODE, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.GAME_MODE, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.MAP_KEY, SETTINGS_FIELD_NORMALIZERS.IDENTIFIER],
    [SETTINGS_CHANGE_KEYS.BOTS_COUNT, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.BOTS_DIFFICULTY, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.BOTS_POLICY_STRATEGY, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.RULES_WINS_NEEDED, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.RULES_AUTO_ROLL, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.RULES_PORTALS_ENABLED, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.HUNT_RESPAWN_ENABLED, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.VEHICLES_PLAYER_1, SETTINGS_FIELD_NORMALIZERS.IDENTIFIER],
    [SETTINGS_CHANGE_KEYS.VEHICLES_PLAYER_2, SETTINGS_FIELD_NORMALIZERS.IDENTIFIER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_SPEED, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_TURN_SENSITIVITY, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_PLANE_SCALE, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_TRAIL_WIDTH, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_GAP_SIZE, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_GAP_FREQUENCY, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_ITEM_AMOUNT, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_FIRE_RATE, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_LOCK_ON_ANGLE, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_NEXT_CHECKPOINT_GLOW_INTENSITY, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_MG_TRAIL_AIM_RADIUS, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_FIGHT_PLAYER_HP, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_FIGHT_MG_DAMAGE, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_PLANAR_MODE, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_PORTAL_COUNT, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.GAMEPLAY_PLANAR_LEVEL_COUNT, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.LOCAL_SHADOW_QUALITY, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.ARCADE_GHOST_DUEL_MODE, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.ARCADE_GHOST_TRAIL_COLLISION_ENABLED, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.RECORDING_PROFILE, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.RECORDING_HUD_MODE, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.CAMERA_PERSPECTIVE_NORMAL, SETTINGS_FIELD_NORMALIZERS.ENUM],
    [SETTINGS_CHANGE_KEYS.CAMERA_PERSPECTIVE_REDUCE_MOTION, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.CAMERA_PERSPECTIVE_SPEED_FOV_ENABLED, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.CAMERA_PERSPECTIVE_SPEED_FOV_INTENSITY, SETTINGS_FIELD_NORMALIZERS.NUMBER],
    [SETTINGS_CHANGE_KEYS.CAMERA_PERSPECTIVE_THRUSTER_EXHAUST_ENABLED, SETTINGS_FIELD_NORMALIZERS.BOOLEAN],
    [SETTINGS_CHANGE_KEYS.CAMERA_PERSPECTIVE_THRUSTER_EXHAUST_INTENSITY, SETTINGS_FIELD_NORMALIZERS.NUMBER],
]);

export const SETTINGS_FIELD_DESCRIPTORS = Object.freeze(
    SETTINGS_CHANGE_PATH_ENTRIES.map(([path, changeKey]) => Object.freeze({
        path,
        defaultPath: path,
        changeKey,
        normalizer: PRESET_FIELD_NORMALIZER_BY_CHANGE_KEY.get(changeKey)
            || SETTINGS_FIELD_NORMALIZERS.CONTRACT,
        presetEligible: PRESET_FIELD_NORMALIZER_BY_CHANGE_KEY.has(changeKey),
    }))
);

const SETTINGS_FIELD_DESCRIPTOR_BY_PATH = new Map(
    SETTINGS_FIELD_DESCRIPTORS.map((descriptor) => [descriptor.path, descriptor])
);

export const SETTINGS_PRESET_FIELD_DESCRIPTORS = Object.freeze(
    SETTINGS_FIELD_DESCRIPTORS.filter((descriptor) => descriptor.presetEligible)
);

export const SETTINGS_PRESET_VALUE_PATHS = Object.freeze(
    SETTINGS_PRESET_FIELD_DESCRIPTORS.map((descriptor) => descriptor.path)
);

export function getSettingsFieldDescriptor(path) {
    const normalizedPath = typeof path === 'string' ? path.trim() : '';
    return normalizedPath ? SETTINGS_FIELD_DESCRIPTOR_BY_PATH.get(normalizedPath) || null : null;
}

export function readSettingsFieldValue(source, path) {
    const descriptor = getSettingsFieldDescriptor(path);
    if (!descriptor || !source || typeof source !== 'object') return undefined;

    let cursor = source;
    for (const segment of descriptor.path.split('.')) {
        if (!cursor || typeof cursor !== 'object'
            || !Object.prototype.hasOwnProperty.call(cursor, segment)) {
            return undefined;
        }
        cursor = cursor[segment];
    }
    return cursor;
}
