import { WIND_CATHEDRAL_WORLD_LIGHTING, WIND_CATHEDRAL_WORLD_LIGHTS } from './world_appearance.js';
import { parcoursRules, V130_BOT_SPAWNS } from './parcours_pack_v130_shared.js';
import { CHRONO_SPILLWAY_MAP } from './parcours_pack_v130_chrono_spillway.js';


export const PARCOURS_PACK_V130_MAPS = Object.freeze({
    micro_maw: {
        name: 'Mikro-Maul',
        size: [132, 50, 150],
        scaleAuthoredAnchors: true,
        preferAuthoredPortals: true,
        itemSpawnMode: 'anchor-only',
        itemRespawnSeconds: 30,
        itemRespawnOnDeath: true,
        fivePortalsExit: { pos: [55, 16, -68], color: 0xffcc44 },
        portalLevels: [12, 18, 24],
        obstacles: [
            { pos: [-44, 9, -42], size: [18, 4, 22], kind: 'foam' },
            // Split around CP02 (z -22, radius 5.4): the ring is the opening in this wall.
            { pos: [-28, 16, -35.7], size: [8, 26, 14.6] },
            { pos: [-28, 16, -7], size: [8, 26, 12] },
            { pos: [-12, 16, -4], size: [10, 30, 18], tunnel: { radius: 5.1, axis: 'x' } },
            { pos: [8, 13, 16], size: [24, 4, 18], kind: 'foam' },
            { pos: [20, 18, 26], size: [4, 24, 8] },
            { pos: [30, 10, 8], size: [8, 4, 8] },
            { pos: [42, 18, -18], size: [10, 30, 18], tunnel: { radius: 5.0, axis: 'x' } },
            { pos: [42, 11, -18], size: [24, 4, 22], kind: 'foam' },
            { pos: [50, 6.2, -46], size: [18, 4, 18], kind: 'foam' },
            { pos: [-4, 14, 34], size: [4, 18, 4] },
            { pos: [18, 15, -30], size: [4, 18, 4] },
            { pos: [36, 15, -38], size: [4, 18, 4] },
            { pos: [-36, 12, -7], size: [7, 15, 9], kind: 'foam' },
            { pos: [14, 14, -12], size: [9, 16, 10], kind: 'foam' },
            { pos: [51, 12, -65], size: [24, 4, 22], kind: 'foam' },
        ],
        portals: [],
        gates: [
            {
                id: 'mm_boost_open',
                type: 'boost',
                pos: [12, 16, 14],
                forward: [1, 0, -0.3],
                params: { duration: 0.9, forwardImpulse: 30, bonusSpeed: 36, cooldown: 0.8 },
            },
        ],
        playerSpawn: { x: -54, y: 12, z: -50 },
        botSpawns: V130_BOT_SPAWNS.micro_maw,
        staticTurrets: [
            { id: 'mm_mg_pillar', weapon: 'mg', pos: [24, 21, 27], range: 42, cooldown: 1.3, damage: 2, phase: 1.1, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
        ],
        items: [
            { id: 'mm_speed_entry', type: 'item_battery', pickupType: 'SPEED_UP', x: -30, y: 14, z: -22, weight: 1.1 },
            { id: 'mm_shield_precision', type: 'item_shield', pickupType: 'SHIELD', x: 16, y: 18, z: 12, weight: 1.0 },
            { id: 'mm_rocket_pocket', type: 'item_rocket', pickupType: 'ROCKET_WEAK', x: -40, y: 14, z: -30, weight: 1.0 },
            { id: 'mm_ghost_finish', type: 'item_coin', pickupType: 'GHOST', x: 48, y: 17, z: -40, weight: 0.8 },
        ],
        missions: [
            { type: 'TIME_TRIAL', params: { target: 30 }, weight: 1.8 },
            { type: 'NO_DAMAGE', params: {}, weight: 0.9 },
        ],
        parcours: {
            enabled: true,
            routeId: 'micro_maw_v1',
            rules: parcoursRules({
                resetOnDeath: false,
                resetToLastValid: true,
                maxSegmentTimeMs: 9000,
                cooldownMs: 380,
                wrongOrderCooldownMs: 520,
                wrongOrderPenaltyMs: 1000,
                errorIndicatorMs: 1000,
            }),
            checkpoints: [
                { id: 'CP01', type: 'entry', pos: [-44, 12, -42], radius: 6.5, forward: [1, 0, 0.6] },
                { id: 'CP02', type: 'gate', pos: [-30, 14, -22], radius: 5.4, forward: [1, 0, 0.5] },
                { id: 'CP03', type: 'tunnel', pos: [-12, 15, -4], radius: 4.2, forward: [1, 0, 0.5] },
                { id: 'CP04', type: 'gate', pos: [8, 16, 16], radius: 5.0, forward: [1, 0, -0.2] },
                { id: 'CP05', type: 'precision', pos: [30, 17, 8], radius: 4.0, forward: [1, 0, -0.8] },
                { id: 'CP06', type: 'tunnel', pos: [42, 18, -18], radius: 4.1, forward: [0.4, 0, -1] },
                { id: 'CP07', type: 'finish_pre', pos: [48, 17, -38], radius: 5.2, forward: [0.2, 0, -1] },
            ],
            finish: { id: 'FINISH', type: 'finish', pos: [52, 16, -52], radius: 6.8, forward: [0.2, 0, -1] },
        },
    },
    mirror_docks: {
        name: 'Spiegelwerft',
        size: [240, 65, 170],
        scaleAuthoredAnchors: true,
        preferAuthoredPortals: true,
        itemSpawnMode: 'anchor-only',
        itemRespawnSeconds: 30,
        itemRespawnOnDeath: true,
        fivePortalsExit: { pos: [108, 24, -53], color: 0xffcc44 },
        portalLevels: [16, 24, 34],
        obstacles: [
            { pos: [-82, 13, 0], size: [18, 4, 28], kind: 'foam' },
            { pos: [-42, 9.2, 0], size: [52, 4, 10] },
            { pos: [-8, 15.4, -34], size: [52, 4, 12] },
            { pos: [-6, 12.2, 34], size: [58, 4, 18], kind: 'foam' },
            { pos: [24, 15.6, 0], size: [24, 4, 36], kind: 'foam' },
            { pos: [48, 18, -18], size: [34, 4, 12] },
            { pos: [48, 18, 18], size: [34, 4, 12], kind: 'foam' },
            { pos: [70, 28, 0], size: [10, 32, 44], tunnel: { radius: 4.4, axis: 'x' } },
            { pos: [88, 14.2, -30], size: [26, 4, 20], kind: 'foam' },
            { pos: [-8, 18, -52], size: [70, 14, 4], kind: 'foam' },
            { pos: [-8, 18, 52], size: [70, 14, 4], kind: 'foam' },
            { pos: [-3, 25, -47], size: [48, 8, 5], kind: 'foam' },
            { pos: [1, 23, 47], size: [38, 8, 5], kind: 'foam' },
            { pos: [36, 22, 29], size: [8, 15, 7], kind: 'foam' },
            { pos: [91, 21, -52], size: [26, 4, 18], kind: 'foam' },
        ],
        portals: [
            { a: [2, 23, -58], b: [18, 24, -16], color: 0x44ccff },
            { a: [2, 22, 58], b: [18, 24, 16], color: 0xff88cc },
        ],
        gates: [
            {
                id: 'md_left_boost',
                type: 'boost',
                pos: [-18, 22, -28],
                forward: [1, 0, 0.8],
                params: { duration: 0.8, forwardImpulse: 36, bonusSpeed: 42, cooldown: 0.9 },
            },
        ],
        playerSpawn: { x: -94, y: 16, z: 0 },
        botSpawns: V130_BOT_SPAWNS.mirror_docks,
        staticTurrets: [
            { id: 'md_mg_right', weapon: 'mg', pos: [0, 29, 42], range: 38, cooldown: 1.5, damage: 2, phase: 0.4, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'md_mg_merge', weapon: 'mg', pos: [44, 34, 29], range: 40, cooldown: 1.6, damage: 2, phase: 1.4, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'md_mg_exit', weapon: 'mg', pos: [82, 34, 7], range: 35, cooldown: 1.7, damage: 2, phase: 0.9, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
        ],
        items: [
            { id: 'md_speed_left', type: 'item_battery', pickupType: 'SPEED_UP', x: -16, y: 24, z: -32, weight: 1.2 },
            { id: 'md_shield_right', type: 'item_shield', pickupType: 'SHIELD', x: -12, y: 22, z: 34, weight: 1.1 },
            { id: 'md_rocket_merge', type: 'item_rocket', pickupType: 'ROCKET_WEAK', x: 14, y: 25, z: -4, weight: 1.0 },
        ],
        missions: [
            { type: 'TIME_TRIAL', params: { target: 46 }, weight: 1.5 },
            { type: 'TRAIL_MASTER', params: { target: 100 }, weight: 0.9 },
        ],
        parcours: {
            enabled: true,
            routeId: 'mirror_docks_v1',
            rules: parcoursRules({
                maxSegmentTimeMs: 12000,
                cooldownMs: 420,
                wrongOrderCooldownMs: 600,
                wrongOrderPenaltyMs: 1800,
                errorIndicatorMs: 1200,
            }),
            checkpoints: [
                { id: 'CP01', type: 'entry', pos: [-82, 16, 0], radius: 6.8, forward: [1, 0, 0] },
                { id: 'CP02', type: 'gate', pos: [-56, 18, 0], radius: 5.8, forward: [1, 0, 0] },
                {
                    id: 'CP03',
                    type: 'branch_entry',
                    pos: [-30, 20, 0],
                    radius: 5.4,
                    forward: [1, 0, 0],
                    nextIds: ['CP04_LEFT', 'CP04_RIGHT'],
                },
                {
                    id: 'CP04_LEFT',
                    type: 'branch_precision',
                    pos: [-6, 23, -34],
                    radius: 4.6,
                    forward: [1, 0, 0.8],
                    nextIds: ['CP05'],
                },
                {
                    id: 'CP04_RIGHT',
                    type: 'branch_boost',
                    pos: [-4, 21, 34],
                    radius: 5.8,
                    forward: [1, 0, -0.8],
                    nextIds: ['CP05'],
                },
                { id: 'CP05', type: 'gate', pos: [24, 24, 0], radius: 5.4, forward: [1, 0, 0] },
                { id: 'CP06', type: 'split', pos: [48, 26, -18], radius: 5.0, forward: [1, 0, 0.4] },
                { id: 'CP06_R', type: 'split', aliasOf: 'CP06', pos: [48, 26, 18], radius: 5.0, forward: [1, 0, -0.4] },
                { id: 'CP07', type: 'tunnel', pos: [70, 28, 0], radius: 4.4, forward: [1, 0, -0.4] },
                { id: 'CP08', type: 'finish_pre', pos: [86, 26, -22], radius: 5.2, forward: [1, 0, -0.8] },
            ],
            finish: { id: 'FINISH', type: 'finish', pos: [94, 24, -38], radius: 6.8, forward: [1, 0, -0.8] },
        },
    },
    glass_serpent: {
        name: 'Glasschlange',
        size: [260, 80, 200],
        scaleAuthoredAnchors: true,
        preferAuthoredPortals: true,
        itemSpawnMode: 'anchor-only',
        itemRespawnSeconds: 30,
        itemRespawnOnDeath: true,
        fivePortalsExit: { pos: [106, 32, 85], color: 0xffcc44 },
        portalLevels: [20, 36, 48],
        // Balcony slabs sit just below their rings (P5): the ring centres stay free.
        obstacles: [
            { pos: [-116, 10, -36], size: [22, 4, 24], kind: 'foam' },
            { shape: 'tube', kind: 'hard', start: [-98, 22, -28], end: [-54, 26, 18], radius: 5.0 },
            { pos: [-18, 21.6, 34], size: [42, 4, 16], kind: 'foam' },
            { shape: 'tube', kind: 'hard', start: [-16, 31, 34], end: [42, 36, -18], radius: 4.8 },
            { shape: 'tube', kind: 'hard', start: [42, 36, -18], end: [68, 38, -42], radius: 4.2 },
            { pos: [72, 33.2, 10], size: [44, 4, 18], kind: 'foam' },
            { pos: [98, 31.6, -6], size: [26, 4, 34], kind: 'foam' },
            { shape: 'tube', kind: 'hard', start: [98, 40, -6], end: [116, 38, 28], radius: 4.6 },
            { pos: [116, 30.6, 28], size: [12, 4, 12] },
            { pos: [116, 25.6, 52], size: [34, 4, 20], kind: 'foam' },
            { pos: [-52, 18, 42], size: [90, 4, 5], kind: 'foam' },
            { pos: [62, 28, -58], size: [70, 4, 5], kind: 'foam' },
            { pos: [16, 27, 15], size: [24, 4, 18], kind: 'foam' },
            { pos: [55, 31, -47], size: [30, 4, 10], kind: 'foam' },
            { pos: [82, 35, 12], size: [28, 4, 15], kind: 'foam' },
            { pos: [101, 28, 79], size: [28, 4, 20], kind: 'foam' },
            { pos: [61, 40, -51], size: [25, 6, 3], kind: 'foam' },
        ],
        portals: [
            { a: [66, 26, -58], b: [24, 34, -10], color: 0x66e6ff },
        ],
        gates: [
            {
                id: 'gs_boost_s_entry',
                type: 'boost',
                pos: [-88, 22, -18],
                forward: [1, 0, 0.6],
                params: { duration: 1.2, forwardImpulse: 42, bonusSpeed: 50, cooldown: 0.9 },
            },
            {
                id: 'gs_sling_balcony',
                type: 'slingshot',
                pos: [58, 38, 2],
                forward: [1, 0.2, 0.4],
                up: [0, 1, 0],
                params: { duration: 1.2, forwardImpulse: 28, liftImpulse: 8, cooldown: 1.2 },
            },
            {
                id: 'gs_boost_exit',
                type: 'boost',
                pos: [98, 40, -6],
                forward: [1, -0.1, 0.8],
                params: { duration: 0.9, forwardImpulse: 38, bonusSpeed: 46, cooldown: 0.8 },
            },
        ],
        playerSpawn: { x: -128, y: 20, z: -38 },
        botSpawns: V130_BOT_SPAWNS.glass_serpent,
        staticTurrets: [
            { id: 'gs_rocket_balcony', weapon: 'rocket', pos: [76, 47, 24], range: 53, cooldown: 4.0, rocketType: 'ROCKET_MEDIUM', phase: 0.7, destructible: true, maxHp: 80, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'gs_mg_precision', weapon: 'mg', pos: [111, 44, -20], range: 35, cooldown: 1.6, damage: 2, phase: 1.3, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
        ],
        items: [
            { id: 'gs_shield_choice', type: 'item_shield', pickupType: 'SHIELD', x: 39, y: 38, z: -17, weight: 1.0 },
            { id: 'gs_rocket_outer', type: 'item_rocket', pickupType: 'ROCKET_MEDIUM', x: 67, y: 44, z: 9, weight: 1.0 },
            { id: 'gs_speed_balcony', type: 'item_battery', pickupType: 'SPEED_UP', x: 81, y: 43, z: 11, weight: 1.0 },
            { id: 'gs_shield_merge', type: 'item_shield', pickupType: 'SHIELD', x: 98, y: 42, z: -4, weight: 1.0 },
        ],
        missions: [
            { type: 'TIME_TRIAL', params: { target: 56 }, weight: 1.5 },
            { type: 'ITEM_CHAIN', params: { target: 3 }, weight: 0.8 },
        ],
        parcours: {
            enabled: true,
            routeId: 'glass_serpent_v1',
            rules: parcoursRules({
                maxSegmentTimeMs: 13500,
                cooldownMs: 420,
                wrongOrderCooldownMs: 620,
                errorIndicatorMs: 1300,
            }),
            checkpoints: [
                { id: 'CP01', type: 'entry', pos: [-116, 20, -36], radius: 7.0, forward: [1, 0, 0.5] },
                { id: 'CP02', type: 'gate', pos: [-88, 22, -18], radius: 5.8, forward: [1, 0, 0.7] },
                { id: 'CP03', type: 'tunnel', pos: [-54, 26, 18], radius: 5.0, forward: [1, 0, 0.3] },
                { id: 'CP04', type: 'gate', pos: [-18, 30, 34], radius: 5.4, forward: [1, 0, -0.2] },
                { id: 'CP05', type: 'gate', pos: [16, 34, 10], radius: 5.2, forward: [1, 0, -0.6] },
                {
                    id: 'CP06',
                    type: 'branch_entry',
                    pos: [42, 36, -18],
                    radius: 5.0,
                    forward: [1, 0, -0.4],
                    nextIds: ['CP07_TUBE', 'CP07_BALCONY'],
                },
                {
                    id: 'CP07_TUBE',
                    type: 'branch_tunnel',
                    pos: [68, 38, -42],
                    radius: 4.2,
                    forward: [1, 0, 0.5],
                    nextIds: ['CP08'],
                },
                {
                    id: 'CP07_BALCONY',
                    type: 'branch_gate',
                    pos: [72, 42, 10],
                    radius: 5.8,
                    forward: [1, -0.1, -0.4],
                    nextIds: ['CP08'],
                },
                { id: 'CP08', type: 'gate', pos: [98, 40, -6], radius: 5.4, forward: [1, 0, 0.7] },
                { id: 'CP09', type: 'precision', pos: [116, 38, 28], radius: 4.4, forward: [0.2, -0.1, 1] },
                { id: 'CP10', type: 'finish_pre', pos: [120, 34, 52], radius: 5.4, forward: [-0.4, -0.1, 1] },
            ],
            finish: { id: 'FINISH', type: 'finish', pos: [112, 32, 66], radius: 7.0, forward: [-0.4, 0, 1] },
        },
    },
    storm_switchyard: {
        name: 'Sturmweiche',
        size: [280, 70, 210],
        scaleAuthoredAnchors: true,
        preferAuthoredPortals: true,
        itemSpawnMode: 'anchor-only',
        itemRespawnSeconds: 30,
        itemRespawnOnDeath: true,
        fivePortalsExit: { pos: [123, 22, 78], color: 0xffcc44 },
        portalLevels: [14, 28, 42],
        obstacles: [
            { pos: [-104, 11, 0], size: [24, 4, 30], kind: 'foam' },
            { pos: [-76, 7.2, -28], size: [38, 4, 12] },
            { pos: [-42, 18, -28], size: [10, 30, 18], tunnel: { radius: 4.8, axis: 'x' } },
            { pos: [-10, 13.8, 0], size: [28, 4, 40], kind: 'foam' },
            { pos: [18, 9.4, -42], size: [46, 4, 16], kind: 'foam' },
            { pos: [18, 28.6, 34], size: [34, 4, 12] },
            { pos: [48, 19.4, 0], size: [30, 4, 38], kind: 'foam' },
            { pos: [76, 21.8, -24], size: [36, 4, 12] },
            { pos: [96, 20, -4], size: [24, 4, 16] },
            { pos: [96, 20, 24], size: [24, 4, 16], kind: 'foam' },
            { pos: [110, 15.6, 44], size: [34, 4, 18], kind: 'foam' },
            { pos: [20, 18, -62], size: [110, 5, 5], kind: 'foam' },
            { pos: [20, 18, 58], size: [110, 5, 5], kind: 'foam' },
            { pos: [20, 24, 0], size: [6, 34, 6] },
            { pos: [48, 26, -20], size: [6, 34, 6] },
            { pos: [78, 28, 12], size: [6, 34, 6] },
            { pos: [2, 17, -31], size: [8, 16, 7], kind: 'foam' },
            { pos: [36, 21, -32], size: [8, 15, 7], kind: 'foam' },
            { pos: [24, 30, 44], size: [24, 4, 10], kind: 'foam' },
            { pos: [46, 32, 34], size: [8, 13, 8], kind: 'foam' },
            { pos: [118, 18, 73], size: [28, 4, 22], kind: 'foam' },
        ],
        portals: [
            { a: [31, 19, -61], b: [44, 28, -13], color: 0x33ddff },
            { a: [29, 36, 53], b: [44, 30, 13], color: 0xcc88ff },
        ],
        gates: [
            {
                id: 'ss_low_boost',
                type: 'boost',
                pos: [18, 18, -42],
                forward: [1, 0, 0.8],
                params: { duration: 1.0, forwardImpulse: 38, bonusSpeed: 46, cooldown: 0.9 },
            },
            {
                id: 'ss_merge_boost',
                type: 'boost',
                pos: [54, 28, -2],
                forward: [1, 0, -0.4],
                params: { duration: 0.8, forwardImpulse: 34, bonusSpeed: 40, cooldown: 0.8 },
            },
        ],
        playerSpawn: { x: -118, y: 14, z: 0 },
        botSpawns: V130_BOT_SPAWNS.storm_switchyard,
        staticTurrets: [
            { id: 'ss_mg_low_entry', weapon: 'mg', pos: [-1, 24, -57], range: 39, cooldown: 1.6, damage: 2, phase: 0.4, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'ss_mg_low_exit', weapon: 'mg', pos: [41, 25, -54], range: 39, cooldown: 1.7, damage: 2, phase: 1.2, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'ss_rocket_cp07', weapon: 'rocket', pos: [82, 35, -41], range: 54, cooldown: 4.2, rocketType: 'ROCKET_MEDIUM', phase: 0.8, destructible: true, maxHp: 80, allowedModes: ['HUNT', 'ARCADE'] },
        ],
        items: [
            { id: 'ss_speed_low', type: 'item_battery', pickupType: 'SPEED_UP', x: 18, y: 20, z: -42, weight: 1.2 },
            { id: 'ss_rocket_high', type: 'item_rocket', pickupType: 'ROCKET_MEDIUM', x: 18, y: 39, z: 34, weight: 1.0 },
            { id: 'ss_shield_mid', type: 'item_shield', pickupType: 'SHIELD', x: 43, y: 30, z: 4, weight: 1.0 },
            { id: 'ss_shield_finish', type: 'item_shield', pickupType: 'SHIELD', x: 107, y: 26, z: 39, weight: 1.0 },
        ],
        missions: [
            { type: 'TIME_TRIAL', params: { target: 62 }, weight: 1.4 },
            { type: 'CLOSE_CALL', params: { target: 2 }, weight: 0.8 },
        ],
        parcours: {
            enabled: true,
            routeId: 'storm_switchyard_v1',
            rules: parcoursRules({
                resetToLastValid: true,
                wrongOrderPenaltyMs: 2200,
            }),
            checkpoints: [
                { id: 'CP01', type: 'entry', pos: [-104, 14, 0], radius: 7.0, forward: [1, 0, -0.4] },
                { id: 'CP02', type: 'gate', pos: [-76, 16, -28], radius: 5.8, forward: [1, 0, 0] },
                { id: 'CP03', type: 'tunnel', pos: [-42, 18, -28], radius: 4.8, forward: [1, 0, 0.6] },
                {
                    id: 'CP04',
                    type: 'branch_entry',
                    pos: [-10, 22, 0],
                    radius: 5.2,
                    forward: [1, 0, 0],
                    nextIds: ['CP05_LOW', 'CP05_HIGH'],
                },
                {
                    id: 'CP05_LOW',
                    type: 'branch_boost',
                    pos: [18, 18, -42],
                    radius: 5.6,
                    forward: [1, 0, 0.8],
                    nextIds: ['CP06'],
                },
                {
                    id: 'CP05_HIGH',
                    type: 'branch_precision',
                    pos: [18, 36, 34],
                    radius: 4.4,
                    forward: [1, -0.2, -0.7],
                    nextIds: ['CP06'],
                },
                { id: 'CP06', type: 'gate', pos: [48, 28, 0], radius: 5.6, forward: [1, 0, -0.6] },
                { id: 'CP07', type: 'gate', pos: [76, 30, -24], radius: 5.2, forward: [1, 0, 0.4] },
                { id: 'CP08', type: 'split', pos: [96, 28, -4], radius: 5.0, forward: [1, 0, 0.6] },
                { id: 'CP08_R', type: 'split', aliasOf: 'CP08', pos: [96, 28, 24], radius: 5.0, forward: [1, 0, 0.6] },
                { id: 'CP09', type: 'finish_pre', pos: [110, 24, 44], radius: 5.4, forward: [0.4, 0, 1] },
            ],
            finish: { id: 'FINISH', type: 'finish', pos: [116, 22, 58], radius: 7.0, forward: [0.4, 0, 1] },
        },
    },
    wind_cathedral: {
        name: 'Windkathedrale',
        size: [200, 120, 200],
        lighting: WIND_CATHEDRAL_WORLD_LIGHTING,
        glbModels: [{ id: 'wind-cathedral-world', url: 'assets/maps/wind_cathedral/glb/01_world.glb',
            position: [0, -0.12, 0], scale: 1 }],
        glbColliderMode: 'dynamic',
        glbAuthoredObstaclesCollisionOnly: true,
        lights: WIND_CATHEDRAL_WORLD_LIGHTS,
        scaleAuthoredAnchors: true,
        preferAuthoredPortals: true,
        itemSpawnMode: 'anchor-only',
        itemRespawnSeconds: 30,
        itemRespawnOnDeath: true,
        fivePortalsExit: { pos: [-72, 22, -53], color: 0xffcc44 },
        portalLevels: [18, 42, 68, 92],
        obstacles: [
            { pos: [-64, 13, 0], size: [24, 4, 30], kind: 'foam' },
            { pos: [-38, 13.2, 0], size: [30, 4, 18] },
            { pos: [-14, 25.8, -22], size: [14, 4, 14], kind: 'foam' },
            { pos: [8, 39.6, -34], size: [16.5, 4, 10.5] },
            { pos: [30, 50, -18], size: [22, 4, 12], kind: 'foam' },
            { pos: [30, 50, 18], size: [22, 4, 12], kind: 'foam' },
            { pos: [48, 59.6, 0], size: [18, 4, 21] },
            { pos: [24, 74.8, 36], size: [12, 4, 12] },
            { pos: [-8, 83.8, 30], size: [36, 4, 16], kind: 'foam' },
            { pos: [-34, 78, 0], size: [10, 34, 42], tunnel: { radius: 4.8, axis: 'x' } },
            { pos: [-52, 30.6, -20], size: [15, 4, 9], kind: 'foam' },
            { pos: [-60, 50, -42], size: [6, 88, 6] },
            { pos: [-60, 50, 42], size: [6, 88, 6] },
            { pos: [14, 58, -58], size: [6, 92, 6] },
            { pos: [14, 58, 58], size: [6, 92, 6] },
            { pos: [46, 70, -42], size: [6, 84, 6] },
            { pos: [46, 70, 42], size: [6, 84, 6] },
            { pos: [20, 52, 0], size: [120, 4, 120], kind: 'foam' },
            { pos: [-26, 28, -15], size: [20, 4, 14], kind: 'foam' },
            { pos: [18, 43, -24], size: [20, 4, 12], kind: 'foam' },
            { pos: [38, 63, 28], size: [18, 4, 14], kind: 'foam' },
            { pos: [-20, 84, 35], size: [24, 4, 14], kind: 'foam' },
            { pos: [-73, 18, -49], size: [26, 4, 20], kind: 'foam' },
        ],
        portals: [
            { a: [18, 48, -52], b: [-12, 50, -24], color: 0xbbeeff },
            { a: [18, 48, 52], b: [-12, 50, 24], color: 0xbbeeff },
        ],
        gates: [
            {
                id: 'wc_sling_aisle',
                type: 'slingshot',
                pos: [-14, 34, -22],
                forward: [1, 0.6, -0.3],
                up: [0, 1, 0],
                params: { duration: 1.5, forwardImpulse: 26, liftImpulse: 16, cooldown: 1.3 },
            },
            {
                id: 'wc_sling_tower',
                type: 'slingshot',
                pos: [30, 58, 0],
                forward: [0.8, 0.7, 0.6],
                up: [0, 1, 0],
                params: { duration: 1.6, forwardImpulse: 24, liftImpulse: 18, cooldown: 1.4 },
            },
            {
                id: 'wc_boost_roof',
                type: 'boost',
                pos: [-8, 92, 30],
                forward: [-0.8, -0.5, -0.4],
                params: { duration: 1.0, forwardImpulse: 34, bonusSpeed: 42, cooldown: 0.9 },
            },
        ],
        playerSpawn: { x: -78, y: 16, z: 0 },
        botSpawns: V130_BOT_SPAWNS.wind_cathedral,
        staticTurrets: [
            { id: 'wc_mg_aisle', weapon: 'mg', pos: [-25, 38, 10], range: 34, cooldown: 1.7, damage: 2, phase: 0.3, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'wc_mg_tower', weapon: 'mg', pos: [38, 63, -35], range: 34, cooldown: 1.7, damage: 2, phase: 1.1, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'wc_rocket_roof', weapon: 'rocket', pos: [9, 94, 47], range: 42, cooldown: 4.4, rocketType: 'ROCKET_MEDIUM', phase: 0.9, destructible: true, maxHp: 80, allowedModes: ['HUNT', 'ARCADE'] },
            { id: 'wc_mg_descent', weapon: 'mg', pos: [-43, 62, -27], range: 35, cooldown: 1.8, damage: 2, phase: 1.6, destructible: true, maxHp: 55, allowedModes: ['HUNT', 'ARCADE'] },
        ],
        items: [
            { id: 'wc_shield_ascent', type: 'item_shield', pickupType: 'SHIELD', x: -42, y: 24, z: -3, weight: 1.0 },
            { id: 'wc_rocket_upper', type: 'item_rocket', pickupType: 'ROCKET_MEDIUM', x: 42, y: 70, z: 10, weight: 1.0 },
            { id: 'wc_speed_roof', type: 'item_battery', pickupType: 'SPEED_UP', x: -8, y: 94, z: 30, weight: 1.2 },
            { id: 'wc_shield_descent', type: 'item_shield', pickupType: 'SHIELD', x: -39, y: 76, z: -3, weight: 1.0 },
        ],
        missions: [
            { type: 'TIME_TRIAL', params: { target: 65 }, weight: 1.4 },
            { type: 'NO_DAMAGE', params: {}, weight: 0.8 },
        ],
        parcours: {
            enabled: true,
            routeId: 'wind_cathedral_v1',
            rules: parcoursRules({
                maxSegmentTimeMs: 15000,
            }),
            checkpoints: [
                { id: 'CP01', type: 'entry', pos: [-64, 16, 0], radius: 7.0, forward: [1, 0, 0] },
                { id: 'CP02', type: 'gate', pos: [-38, 22, 0], radius: 5.8, forward: [1, 0.3, -0.4] },
                { id: 'CP03', type: 'slingshot', pos: [-14, 34, -22], radius: 5.2, forward: [1, 0.6, -0.4] },
                { id: 'CP04', type: 'gate', pos: [8, 48, -34], radius: 5.4, forward: [1, 0.4, 0.4] },
                { id: 'CP05', type: 'split', pos: [30, 58, -18], radius: 5.0, forward: [1, 0.5, 0.4] },
                { id: 'CP05_R', type: 'split', aliasOf: 'CP05', pos: [30, 58, 18], radius: 5.0, forward: [1, 0.5, -0.4] },
                { id: 'CP06', type: 'gate', pos: [48, 68, 0], radius: 5.4, forward: [-0.4, 0.8, 0.8] },
                { id: 'CP07', type: 'precision', pos: [24, 82, 36], radius: 4.2, forward: [-0.8, 0.4, 0.2] },
                { id: 'CP08', type: 'gate', pos: [-8, 92, 30], radius: 5.2, forward: [-1, -0.4, -0.4] },
                { id: 'CP09', type: 'tunnel', pos: [-34, 78, 0], radius: 4.8, forward: [-0.8, -0.8, -0.4] },
                { id: 'CP10', type: 'finish_pre', pos: [-52, 42, -20], radius: 5.4, forward: [-0.4, -0.9, -0.6] },
            ],
            finish: { id: 'FINISH', type: 'finish', pos: [-64, 24, -34], radius: 7.0, forward: [-0.4, -0.6, -1] },
        },
    },
    chrono_spillway: CHRONO_SPILLWAY_MAP,
});
