const ALL_GAME_MODES = Object.freeze(['CLASSIC', 'ARCADE', 'HUNT']);

export const PICKUP_EXPANSION_DEFINITIONS = Object.freeze({
    TRAIL_GAP: {
        name: 'Spurluecke', description: 'Der getroffene Gegner erzeugt 10 Sekunden lang keine neue Spur.',
        color: 0x42e8f4, icon: '---', duration: 10,
        selfUsable: false, shootable: true, offensive: true, projectileOnly: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 14, visualKind: 'trail-gap',
        actionRole: 'debuff', effectCategory: 'trail-gap', animationKind: 'phase',
        spawnWeights: { CLASSIC: 0.55, ARCADE: 0.65, HUNT: 0.5 },
        botRule: { self: -0.8, offense: 0.85, defensiveScale: 0, emergencyScale: 0, combatSelf: -0.3 },
    },
    EMP: {
        name: 'EMP', description: 'Entfernt im Radius 20 positive Effekte und Schilde und sperrt Items 15 Sekunden.',
        color: 0x33bbff, icon: 'EMP', duration: 15, pulseRadius: 20,
        selfUsable: true, shootable: false, offensive: true, projectileOnly: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 15, visualKind: 'emp',
        effectCategory: 'disruption', animationKind: 'pulse',
        spawnWeights: { CLASSIC: 0.45, ARCADE: 0.55, HUNT: 0.6 },
        botRule: { self: 0.25, offense: 0, defensiveScale: 0, emergencyScale: 0, combatSelf: 1.2 },
    },
    MAGNET: {
        name: 'Magnet', description: 'Verfuenffacht den Einsammelradius 6 Sekunden lang.',
        color: 0xff4466, icon: 'U', duration: 6, pickupRadiusMultiplier: 5,
        selfUsable: true, shootable: false, offensive: false, projectileOnly: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 16, visualKind: 'magnet',
        effectCategory: 'pickup-range', animationKind: 'orbit',
        spawnWeights: { CLASSIC: 0.5, ARCADE: 0.65, HUNT: 0.55 },
        botRule: { self: 0.6, offense: 0, defensiveScale: 0.25, emergencyScale: 0.1, combatSelf: 0.1 },
    },
    DECOY: {
        name: 'Koeder', description: 'Schuetzt 10 Sekunden lang vor Zielverfolgung.',
        color: 0xff77dd, icon: 'D', duration: 10,
        selfUsable: true, shootable: false, offensive: false, projectileOnly: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 17, visualKind: 'decoy',
        effectCategory: 'targeting', animationKind: 'counter-spin',
        spawnWeights: { CLASSIC: 0.4, ARCADE: 0.5, HUNT: 0.65 },
        botRule: { self: 0.75, offense: 0, defensiveScale: 0.9, emergencyScale: 1.3, combatSelf: 0.4 },
    },
    // Retired: stays resolvable so old maps, saves and replays still load, but never spawns or acts.
    PURGE: {
        name: 'Reinigung', color: 0xffffff, icon: 'P', duration: 0,
        selfUsable: true, shootable: false, offensive: false, projectileOnly: false, playable: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 18, visualKind: 'purge',
        actionRole: 'instant', stackPolicy: 'instant',
        spawnWeights: { CLASSIC: 0, ARCADE: 0, HUNT: 0 },
        botRule: { self: 0, offense: 0, defensiveScale: 0, emergencyScale: 0, combatSelf: 0 },
    },
    SWAP: {
        name: 'Tausch', color: 0xbb66ff, icon: '<>', duration: 0,
        selfUsable: false, shootable: true, offensive: true, projectileOnly: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 15, visualKind: 'swap',
        actionRole: 'instant', stackPolicy: 'instant', animationKind: 'counter-spin',
        spawnWeights: { CLASSIC: 0.3, ARCADE: 0.45, HUNT: 0.5 },
        botRule: { self: -1, offense: 0.7, defensiveScale: 0, emergencyScale: 0, combatSelf: -1 },
    },
    MINE: {
        name: 'Mine', color: 0xff5533, icon: '*', duration: 0, damage: 25,
        selfUsable: true, shootable: false, offensive: true, projectileOnly: false,
        allowedModes: ALL_GAME_MODES, observationSlot: 13, visualKind: 'mine',
        actionRole: 'deployment', stackPolicy: 'instant',
        spawnWeights: { CLASSIC: 0.4, ARCADE: 0.55, HUNT: 0.65 },
        botRule: { self: 0.55, offense: 0.65, defensiveScale: 0.35, emergencyScale: 0.2, combatSelf: 0.8 },
    },
});
