export const LEGACY_MAX_LINES = Object.freeze({
    'src/core/Audio.js': 758,
    'src/core/arcade/ArcadeRunRuntime.js': 1185,
    'src/core/MediaRecorderSystem.js': 1461,
    'src/core/recording/DownloadService.js': 542,
    'src/core/renderer/RecordingCapturePipeline.js': 700,
    'src/core/renderer/camera/RecordingOrbitCameraDirector.js': 508,
    'src/core/config/maps/presets/parcours_pack_v130.js': 620,
    'src/core/main.js': 560,
    'dev/training/src/entities/ai/training/WebSocketTrainerBridge.js': 640,
    'src/entities/systems/PlayerInputSystem.js': 515,
    'src/hunt/KillcamSystem.js': 729,
    'src/shared/contracts/BrowserDemoSurfacePolicyOverrideContract.js': 692,
    'src/shared/contracts/PlatformSurfacePolicyOps.js': 538,
    'src/ui/TouchInputSource.js': 720,
    'src/ui/UIManager.js': 650,
});
