export const LEGACY_MAX_LINES = Object.freeze({
    'src/core/arcade/ArcadeRunRuntime.js': 1530,
    'src/core/GameDebugApi.js': 650,
    'src/core/GameRuntimeFacade.js': 470,
    'src/core/MediaRecorderSystem.js': 1320,
    'src/core/renderer/RecordingCapturePipeline.js': 700,
    'src/core/SettingsManager.js': 585,
    'src/core/config/maps/presets/parcours_pack_v130.js': 620,
    'src/core/main.js': 560,
    'dev/training/src/entities/ai/training/WebSocketTrainerBridge.js': 700,
    'src/entities/systems/PlayerInputSystem.js': 515,
    'src/shared/contracts/BrowserDemoSurfacePolicyOverrideContract.js': 692,
    'src/shared/contracts/PlatformSurfacePolicyOps.js': 538,
    'src/shared/runtime/GameRuntimePorts.js': 420,
    'src/ui/arcade/ArcadeVehicleManager.js': 552,
    'src/ui/MatchFlowUiController.js': 790,
    'src/ui/PauseOverlayController.js': 300,
    'src/ui/TouchInputSource.js': 720,
    'src/ui/UIManager.js': 1225,
});
