// Generated by generate_notre_dame_evolution_assets.py; initial-pose bounds determine placement.
export const NOTRE_DAME_EVOLUTION_MODELS = [
    {
        "id": "notre-dame-evolution-roof",
        "url": "assets/maps/notre_dame_evolution/glb/roof.glb",
        "position": [
            5.309106826782227,
            27.685021972656248,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-nave",
        "url": "assets/maps/notre_dame_evolution/glb/nave.glb",
        "position": [
            -34.54829339981079,
            6.879999983310699,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-transept",
        "url": "assets/maps/notre_dame_evolution/glb/transept.glb",
        "position": [
            16.974999999999998,
            6.879999983310699,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-north",
        "url": "assets/maps/notre_dame_evolution/glb/north.glb",
        "position": [
            -83.03526229858397,
            8.0,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-south",
        "url": "assets/maps/notre_dame_evolution/glb/south.glb",
        "position": [
            -86.32512664794922,
            8.0,
            -6.497103309631347
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-crown",
        "url": "assets/maps/notre_dame_evolution/glb/crown.glb",
        "position": [
            -86.45941009521484,
            8.0,
            -0.2761959075927734
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    }
];
