// Generated by generate_notre_dame_evolution_assets.py; initial-pose bounds determine placement.
export const NOTRE_DAME_EVOLUTION_MODELS = [
    {
        "id": "notre-dame-evolution-roof",
        "url": "assets/maps/notre_dame_evolution/glb/roof.glb",
        "position": [
            5.309106826782227,
            27.685021972656248,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-nave",
        "url": "assets/maps/notre_dame_evolution/glb/nave.glb",
        "position": [
            -34.649422550201415,
            6.879999983310699,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-transept",
        "url": "assets/maps/notre_dame_evolution/glb/transept.glb",
        "position": [
            16.974999999999998,
            6.879999983310699,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-north",
        "url": "assets/maps/notre_dame_evolution/glb/north.glb",
        "position": [
            -82.87344017028808,
            8.0,
            -0.0
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-south",
        "url": "assets/maps/notre_dame_evolution/glb/south.glb",
        "position": [
            -86.2485668182373,
            8.0,
            -4.553165626525878
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    },
    {
        "id": "notre-dame-evolution-crown",
        "url": "assets/maps/notre_dame_evolution/glb/crown.glb",
        "position": [
            -86.24941062927246,
            8.0,
            -1.0499999999999998
        ],
        "rotation": [
            0,
            0,
            0
        ],
        "scale": 1.4,
        "hiddenUntilTriggered": true,
        "fixedTriggeredPlacement": true,
        "animationClock": {
            "mode": "once",
            "clipName": "NotreDameCollapse"
        }
    }
];
