export function createEditorDomRefs(doc = document) {
    return {
        toolButtons: Array.from(doc.querySelectorAll('.tool')),
        subMenus: Array.from(doc.querySelectorAll('.sub-menu')),

        buildDock: doc.getElementById('buildDock'),
        assetStatusText: doc.getElementById('assetStatusText'),
        dockModeBadge: doc.getElementById('dockModeBadge'),
        dockActiveTitle: doc.getElementById('dockActiveTitle'),
        dockActiveDescription: doc.getElementById('dockActiveDescription'),
        dockCategoryTabs: doc.getElementById('dockCategoryTabs'),
        dockCards: doc.getElementById('dockCards'),
        dockRecentList: doc.getElementById('dockRecentList'),
        dockFavoriteList: doc.getElementById('dockFavoriteList'),
        btnDockSelectMode: doc.getElementById('btnDockSelectMode'),
        btnDockFavoriteToggle: doc.getElementById('btnDockFavoriteToggle'),
        btnDockDetailToggle: doc.getElementById('btnDockDetailToggle'),
        btnDockCollapse: doc.getElementById('btnDockCollapse'),
        btnDockViewToggle: doc.getElementById('btnDockViewToggle'),
        btnToggleDockFromScene: doc.getElementById('btnToggleDockFromScene'),
        btnToggleHelp: doc.getElementById('btnToggleHelp'),
        editorHelp: doc.getElementById('editorHelp'),
        dockSearch: doc.getElementById('dockSearch'),
        dockAssetFilter: doc.getElementById('dockAssetFilter'),

        inspectorToolModeBadge: doc.getElementById('inspectorToolModeBadge'),
        inspectorToolTitle: doc.getElementById('inspectorToolTitle'),
        inspectorToolDescription: doc.getElementById('inspectorToolDescription'),

        subSpawn: doc.getElementById("subSpawn"),
        subTunnel: doc.getElementById("subTunnel"),
        subPortal: doc.getElementById("subPortal"),
        subItem: doc.getElementById("subItem"),
        subAircraft: doc.getElementById("subAircraft"),

        selSpawnType: doc.getElementById("selSpawnType"),
        selTunnelType: doc.getElementById("selTunnelType"),
        selPortalType: doc.getElementById("selPortalType"),
        selItemType: doc.getElementById("selItemType"),
        selAircraftType: doc.getElementById("selAircraftType"),

        chkFly: doc.getElementById("chkFly"),
        chkYLayer: doc.getElementById("chkYLayer"),
        numYLayer: doc.getElementById("numYLayer"),
        chkSnap: doc.getElementById("chkSnap"),
        numGrid: doc.getElementById("numGrid"),
        numRotationSnap: doc.getElementById("numRotationSnap"),
        numScaleSnap: doc.getElementById("numScaleSnap"),

        numArenaW: doc.getElementById("numArenaW"),
        numArenaD: doc.getElementById("numArenaD"),
        numArenaH: doc.getElementById("numArenaH"),

        hudObjCount: doc.getElementById("hudObjCount"),

        propPanel: doc.getElementById("propPanel"),
        propObjectId: doc.getElementById("propObjectId"),
        propObjectType: doc.getElementById("propObjectType"),
        propContextRow: doc.getElementById("propContextRow"),
        propContext: doc.getElementById("propContext"),
        propPortalPartnerRow: doc.getElementById('propPortalPartnerRow'),
        propPortalPartner: doc.getElementById('propPortalPartner'),
        propCheckpointOrderRow: doc.getElementById('propCheckpointOrderRow'),
        propCheckpointOrder: doc.getElementById('propCheckpointOrder'),
        propX: doc.getElementById("propX"),
        propZ: doc.getElementById("propZ"),
        propRotationY: doc.getElementById("propRotationY"),
        propGroup: doc.getElementById("propGroup"),
        propSizeRow: doc.getElementById("propSizeRow"),
        propSizeLabel: doc.getElementById("propSizeLabel"),
        propWidthRow: doc.getElementById("propWidthRow"),
        propDepthRow: doc.getElementById("propDepthRow"),
        propHeightRow: doc.getElementById("propHeightRow"),
        propScaleRow: doc.getElementById("propScaleRow"),
        propY: doc.getElementById("propY"),
        propSize: doc.getElementById("propSize"),
        propWidth: doc.getElementById("propWidth"),
        propDepth: doc.getElementById("propDepth"),
        propHeight: doc.getElementById("propHeight"),
        propScale: doc.getElementById("propScale"),

        jsonOutput: doc.getElementById("jsonOutput"),
        btnSaveToGame: doc.getElementById("btnSaveToGame"),
        btnExport: doc.getElementById("btnExport"),
        btnPlaytest: doc.getElementById("btnPlaytest"),
        selPlaytestMode: doc.getElementById("selPlaytestMode"),
        selPlaytestSession: doc.getElementById('selPlaytestSession'),
        btnImport: doc.getElementById("btnImport"),
        btnNew: doc.getElementById("btnNew"),
        btnDelSelected: doc.getElementById("btnDelSelected"),
        btnUndo: doc.getElementById("btnUndo"),
        btnRedo: doc.getElementById("btnRedo"),
        btnCopyJson: doc.getElementById("btnCopyJson"),
        btnDownloadJson: doc.getElementById("btnDownloadJson"),
        btnLoadJsonFile: doc.getElementById("btnLoadJsonFile"),
        jsonFileInput: doc.getElementById("jsonFileInput"),

        exportDialog: doc.getElementById('exportDialog'),
        exportForm: doc.getElementById('exportForm'),
        exportFormView: doc.getElementById('exportFormView'),
        exportResultView: doc.getElementById('exportResultView'),
        exportMapName: doc.getElementById('exportMapName'),
        exportTarget: doc.getElementById('exportTarget'),
        exportConflictModeRow: doc.getElementById('exportConflictModeRow'),
        exportConflictMode: doc.getElementById('exportConflictMode'),
        exportKeyPreview: doc.getElementById('exportKeyPreview'),
        exportFilePreview: doc.getElementById('exportFilePreview'),
        exportConflictNotice: doc.getElementById('exportConflictNotice'),
        exportValidationSummary: doc.getElementById('exportValidationSummary'),
        exportValidationList: doc.getElementById('exportValidationList'),
        exportWarningAcknowledgeRow: doc.getElementById('exportWarningAcknowledgeRow'),
        exportWarningAcknowledge: doc.getElementById('exportWarningAcknowledge'),
        btnExportCancel: doc.getElementById('btnExportCancel'),
        btnExportConfirm: doc.getElementById('btnExportConfirm'),
        exportResultSummary: doc.getElementById('exportResultSummary'),
        exportResultPaths: doc.getElementById('exportResultPaths'),
        btnExportPlay: doc.getElementById('btnExportPlay'),
        btnExportOpenFolder: doc.getElementById('btnExportOpenFolder'),
        btnExportCopyKey: doc.getElementById('btnExportCopyKey'),
        btnExportClose: doc.getElementById('btnExportClose'),

        dirtyStateBadge: doc.getElementById('dirtyStateBadge'),
        validationStateBadge: doc.getElementById('validationStateBadge'),
        workspaceStatusMessage: doc.getElementById('workspaceStatusMessage'),
        validationList: doc.getElementById('validationList'),
        recoveryBanner: doc.getElementById('recoveryBanner'),
        btnRestoreAutosave: doc.getElementById('btnRestoreAutosave'),
        btnDismissAutosave: doc.getElementById('btnDismissAutosave'),
        objectSearch: doc.getElementById('objectSearch'),
        objectTypeFilter: doc.getElementById('objectTypeFilter'),
        objectList: doc.getElementById('objectList'),
        btnDuplicateSelected: doc.getElementById('btnDuplicateSelected'),
        btnToggleSelectedVisibility: doc.getElementById('btnToggleSelectedVisibility'),
        btnToggleSelectedLock: doc.getElementById('btnToggleSelectedLock'),
        btnGroupMarked: doc.getElementById('btnGroupMarked'),
        btnDeleteMarked: doc.getElementById('btnDeleteMarked'),
        btnDuplicateMarked: doc.getElementById('btnDuplicateMarked'),
        btnTransformMarked: doc.getElementById('btnTransformMarked'),
        layerList: doc.getElementById('layerList'),
        prefabList: doc.getElementById('prefabList'),
        btnViewPerspective: doc.getElementById('btnViewPerspective'),
        btnViewTop: doc.getElementById('btnViewTop'),
        btnViewFront: doc.getElementById('btnViewFront'),
        btnViewSide: doc.getElementById('btnViewSide'),
        btnFocusSelection: doc.getElementById('btnFocusSelection'),

        editorModalBackdrop: doc.getElementById('editorModalBackdrop'),
        editorModalTitle: doc.getElementById('editorModalTitle'),
        editorModalMessage: doc.getElementById('editorModalMessage'),
        editorModalInput: doc.getElementById('editorModalInput'),
        btnEditorModalCancel: doc.getElementById('btnEditorModalCancel'),
        btnEditorModalConfirm: doc.getElementById('btnEditorModalConfirm'),
    };
}
